version: "3.7"
services:
  blog:
    container_name: blogjava
    network_mode: bridge
    depends_on:
      - postgres_db
    ports:
      - "9000:9000"
    image: blogjava
  postgres_db:
    container_name: blogpostg
    network_mode: bridge
    ports:
      - "5432:5432" 
    image: postgres:latest
    environment:
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: 123456